version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_ecommerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: projet_web_slam
      MYSQL_USER: SaumonDeLuxe
      MYSQL_PASSWORD: rootpwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd/Base.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ecommerce
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpwd
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
